README.md

Added some more information regarding configuration and added more features info

Updated Readme with more setup text

---

dist/css/style_plugin.css
dist/javascripts/slider.js
dist/javascripts/zype_wp.js
resources/controllers/Consumer/Gridscreen.php
resources/views/grid_screen_index.php
resources/views/video_single.php

1) The video is not played on the demo site www.zypeplugin.com. Fix it, and test to make sure this fix is implemented for all videos within the plugin.
2) All "landscape" thumbnails for a separate presentation of the playlist must have a ratio of 16: 9.
3) Ratio at playlists
4) Thumbnails of "Poster" size images are not currently updated
5) Remove the extra space on the right in the thumbnail pages
6) Video rows within the “single playlist” view
7) Arrange the arrows in the center in height.
8) Add a playlist title on the video page(<h2>)
9) Change "View all" to "See all".
10) Add a video title under the video player and make an <h2>
11) Thumbnail name/title
12) Playlist headings

- Sprint 10:

---

README.md

@svetdev can you review and approve please?

Small tweaks to monetization instructions

---

dist/javascripts/zype_wp.js
resources/controllers/Consumer/PlayerAJAX.php
resources/models/Player.php
resources/views/livestream.php
resources/views/partial/player_embed.php
resources/views/video_single.php

- autoplay option disabled by default

- videos now not loading preview on free or paid videos

---

.gitignore
zype.php

Version update and description update for plugin

updating plugin description and version in zype.php

---

src/Themosis/Route/Route.php
zype.php

This should be merged into https://github.com/zype/zype-wordpress-plugin/pull/22 and then that into master

CORE-1209 - Regex error in Zype Wordpress Plugin

---

resources/controllers/Admin.php
resources/lib/Zype/config.php
resources/views/admin/api_keys.php
resources/views/grid_screen_index.php

JIRA: https://zypeinc.atlassian.net/browse/CORE-1418
Added optional pagination for the playlists.

CORE 1418 - Optional Pagination

---

dist/css/zype_forms/plans.css
resources/controllers/Consumer/Gridscreen.php
resources/views/auth/subscription_checkout.php

JIRA: https://zypeinc.atlassian.net/browse/CORE-1597

CORE 1597 - Mask payment form and closes input fields

---

resources/views/video_single.php

[JIRA](https://zypeinc.atlassian.net/browse/CORE-1700)

CORE 1700 - Fix duration displayed

---

resources/providers/HooksService.php
resources/shortcodes.php

I believe we should not be setting a dependency on the current theme for the slick loading. I have also moved a variable setting into a section where the key should actually be available.

quick fixes- slick theme and attr checking

---

dist/css/style_plugin.css
dist/css/zype_forms/regform.css
dist/css/zype_forms/single_video.css
dist/css/zype_forms/single_video.scss
dist/css/zype_forms/subscription_button.css
dist/javascripts/zype_wp.js
resources/controllers/Admin.php
resources/controllers/Consumer/Auth.php
resources/controllers/Consumer/Subscriptions.php
resources/lib/Zype/config.php
resources/providers/HooksService.php
resources/services/Auth.php
resources/shortcodes.php
resources/views/admin/braintree.php
resources/views/auth/login_ajax.php
resources/views/auth/plans.php
resources/views/auth/signup_ajax.php
resources/views/auth/subscription_checkout.php
resources/views/subscribe_button.php
zype.php

[CORE-1895](https://zypeinc.atlassian.net/browse/CORE-1895)
[CORE-1894](https://zypeinc.atlassian.net/browse/CORE-1894)
[CORE-2000](https://zypeinc.atlassian.net/browse/CORE-2000)

Core 1895 - Add consumer flow for using the subscription short code on WP websites

---

resources/views/admin/braintree.php
resources/views/auth/subscription_checkout.php

[JIRA](https://zypeinc.atlassian.net/browse/CORE-1873)

CORE 2108 - Text changes

---

resources/controllers/Admin.php
resources/controllers/Consumer/Auth.php
resources/controllers/Consumer/Subscriptions.php
resources/views/admin/braintree.php
resources/views/auth/login_ajax.php
resources/views/auth/subscription_checkout.php
resources/views/subscribe_button.php

[JIRA](https://zypeinc.atlassian.net/browse/CORE-2112)

CORE 2112 - Fix redirections

---

dist/css/style_plugin.css
dist/css/zype_forms/auth/change_credit_card.css
dist/css/zype_forms/plans.css
resources/controllers/Consumer/Profile.php
resources/providers/HooksService.php
resources/routes.php
resources/views/auth/change_credit_card.php
resources/views/auth/change_password.php
resources/views/auth/profile.php
resources/views/auth/subscription.php

[JIRA](https://zypeinc.atlassian.net/browse/CORE-2382)
Update stripe consumer card in /profile

CORE 2382 - Update stripe consumer credit card

---

resources/views/admin/braintree.php

[JIRA](https://zypeinc.atlassian.net/browse/CORE-2271)

CORE 2271 - Typo on Subscription Short Code description

---

dist/css/zype_forms/plans.css

[JIRA](https://zypeinc.atlassian.net/browse/CORE-2416)

CORE 2416 - Typo on CSS id

---

resources/views/auth/change_credit_card.php
resources/views/auth/subscription_checkout.php

[JIRA](https://zypeinc.atlassian.net/browse/CORE-2338)

CORE 2338 - Accept multiple types of credit cards

---

src/Themosis/Metabox/MetaboxBuilder.php
src/Themosis/PostType/PostTypeBuilder.php
src/Themosis/Taxonomy/TaxField.php
src/Themosis/Taxonomy/TaxonomyBuilder.php
src/Themosis/User/UserFactory.php
src/Themosis/helpers.php

[JIRA](https://zypeinc.atlassian.net/browse/CORE-2391)

CORE 2391 - Sanitizing Themosis

---

resources/controllers/Consumer/Profile.php
resources/lib/Zype/Api.php
resources/lib/Zype/Wrapper.php

[JIRA](https://zypeinc.atlassian.net/browse/CORE-2437)

CORE 2437 - Show only the enabled subscription plans

---

dist/css/style_plugin.css
dist/css/zype_forms/regform.css
dist/css/zype_forms/single_video.css
dist/javascripts/zype_wp.js
resources/controllers/Admin.php
resources/controllers/Consumer/Auth.php
resources/controllers/Consumer/Library.php
resources/controllers/Consumer/Subscriptions.php
resources/controllers/Consumer/Videos.php
resources/helpers.php
resources/lib/Zype/Api.php
resources/lib/Zype/Wrapper.php
resources/lib/Zype/config.php
resources/models/Video.php
resources/models/consumer/VideoEntitlement.php
resources/shortcodes.php
resources/views/admin/braintree.php
resources/views/auth/login_ajax.php
resources/views/auth/signup_ajax.php
resources/views/auth/videos_pagination.php
resources/views/subscribe_button.php
zype.php

[JIRA](https://zypeinc.atlassian.net/browse/CORE-2393)

CORE 2393 - My library shortcode

---

resources/controllers/Consumer/Subscriptions.php

[JIRA](https://zypeinc.atlassian.net/browse/CORE-2316)

CORE 2316 - Fix /subscribe page

---

dist/javascripts/zype_wp.js
resources/controllers/Consumer/Auth.php
resources/controllers/Consumer/Base.php
resources/controllers/Consumer/Videos.php
resources/helpers.php
resources/models/Player.php
resources/providers/HooksService.php
resources/shortcodes.php
resources/views/auth/login.php
resources/views/auth/signup.php
resources/views/partial/player_embed.php
resources/views/video_single.php

[JIRA](https://zypeinc.atlassian.net/browse/CORE-2281)

CORE 2281 - Fix redirects to URL

---

resources/controllers/Admin.php
resources/lib/Zype/Api.php

[Jira](https://zypeinc.atlassian.net/browse/CORE-2570)

CORE 2567 - Fix My Library shortcode and Admin Video Search

---

resources/views/partial/player_embed.php

[JIRA](https://zypeinc.atlassian.net/browse/CORE-2571)

CORE 2571 - Typo on player_embed

---

dist/css/zype_forms/loginform.css
dist/css/zype_forms/plans.css
dist/css/zype_forms/regform.css
dist/javascripts/zype_wp.js
resources/controllers/Admin.php
resources/controllers/Consumer/Monetization.php
resources/controllers/Consumer/Subscriptions.php
resources/lib/Zype/config.php
resources/views/admin/braintree.php
resources/views/auth/cc_form.php
resources/views/auth/login_ajax.php
resources/views/auth/paywall.php
resources/views/auth/subscription_checkout.php
zype.php

[JIRA](https://zypeinc.atlassian.net/browse/CORE-2421)

CORE 2421 - Support Stripe Coupons

---

core.php
dist/css/admin/email_settings.css
resources/admin/plugin.php
resources/controllers/Admin.php
resources/controllers/Consumer/Auth.php
resources/controllers/Consumer/Profile.php
resources/controllers/Consumer/Subscriptions.php
resources/controllers/Consumer/Transaction.php
resources/controllers/Controller.php
resources/controllers/admin/CustomizeUi.php
resources/controllers/admin/EmailSettings.php
resources/lib/Zype/config.php
resources/services/Mailer.php
resources/views/admin/email_settings.php
zype.php

[JIRA](https://zypeinc.atlassian.net/browse/CORE-2754)
@andyzheng547 This one should be merged to mater after #71

CORE 2754 - Allow customers to enable and disable certain automated emails

---

dist/css/zype_forms/plans.css
dist/javascripts/zype_wp.js
resources/controllers/Admin.php
resources/controllers/Consumer/Monetization.php
resources/controllers/Consumer/Profile.php
resources/controllers/Consumer/Subscriptions.php
resources/controllers/Consumer/Videos.php
resources/helpers.php
resources/lib/ApiOperations/All.php
resources/lib/ApiOperations/Create.php
resources/lib/ApiOperations/Retrieve.php
resources/lib/ApiOperations/Update.php
resources/lib/Zype/Api.php
resources/lib/Zype/Api/Playlist.php
resources/lib/Zype/Api/Video.php
resources/lib/Zype/Wrapper.php
resources/models/V2/Base.php
resources/models/V2/Consumer.php
resources/models/V2/Plan.php
resources/models/V2/Playlist.php
resources/providers/HooksService.php
resources/providers/ZypeService.php
resources/services/Access.php
resources/services/Auth.php
resources/shortcodes.php
resources/views/auth/cc_form.php
resources/views/auth/paywall.php
resources/views/auth/plans.php
resources/views/grid_screen_index.php
resources/views/partial/player_embed.php

[JIRA](https://zypeinc.atlassian.net/browse/CORE-2588)

CORE 2588 - Support purchasing of tiered subscriptions

---

resources/views/auth/login.php
resources/views/auth/signup.php
resources/views/partial/player_embed.php
resources/views/video_single.php

[JIRA](https://zypeinc.atlassian.net/browse/CORE-2773)

CORE 2773 - Show the right form when clicking 'Sign in' or 'Join' button

---

resources/lib/Zype/Wrapper.php

[JIRA](https://zypeinc.atlassian.net/browse/CORE-2790)

CORE 2790 - Remove sorting param when retrieving the playlist's videos

---

dist/javascripts/admin/customize_ui.js
resources/controllers/admin/CustomizeUi.php
resources/lib/Zype/config.php
resources/views/admin/customize_ui.php
zype.php

[JIRA](https://zypeinc.atlassian.net/browse/CORE-2423)

CORE 2423 - Add support for light and dark themes

---

resources/helpers.php

[JIRA](https://zypeinc.atlassian.net/browse/CORE-2981)

CORE 2981 - Fix for avoiding spam

---

resources/controllers/Admin.php
resources/lib/Zype/Wrapper.php
resources/models/V2/Base.php

[JIRA](https://zypeinc.atlassian.net/browse/CORE-3044)

CORE 3044 - Fix error when using saving invalid keys

---

resources/config/loading.config.php

[JIRA](https://zypeinc.atlassian.net/browse/CORE-3053)

CORE 3053 - Add ZypeMedia\Controllers\Admin\ to autoload

---

resources/services/Auth.php

Fix the cookie read to actually pull from the cookie

---

resources/views/grid_screen_index.php

[JIRA](https://zypeinc.atlassian.net/browse/CORE-3140)

CORE 3140 - Add pagination=true to playlist URL only if playlist option si enabled

---

resources/controllers/Consumer/Gridscreen.php

[JIRA](https://zypeinc.atlassian.net/browse/CORE-3058)

CORE 3058 - Fix error when playlist shortcode is for an empty playlist.

---

resources/models/V2/Playlist.php
resources/views/grid_screen_index.php
zype.php

[JIRA](https://zypeinc.atlassian.net/browse/CORE-3147)

CORE 3147 - array_map in favor of array_column for PHP 5 customer

---

resources/views/auth/subscription.php

[JIRA](https://zypeinc.atlassian.net/browse/CORE-3195)

CORE 3195 - Fix error when selecting a plan in /profile/subscription/

---

resources/views/auth/plans.php
resources/views/video_single.php
zype.php

[JIRA](https://zypeinc.atlassian.net/browse/CORE-3234)

CORE 3234 - Fix /subscribe page when choosing a plan

---

resources/controllers/Consumer/Subscriptions.php
zype.php

[JIRA](https://zypeinc.atlassian.net/browse/CORE-3234)

CORE 3234 - When accessing to /subscribe redirect to AUTH_URL if the user is not logged in

---

resources/services/Auth.php
zype.php

[JIRA](https://zypeinc.atlassian.net/browse/CORE-3332)

CORE 3332 - Remove zype_wp cookie on logout

---

dist/css/style_plugin.css
dist/css/zype_forms/plans.css
dist/javascripts/zype_wp.js
resources/controllers/Consumer/Monetization.php
resources/lib/Zype/Api/Account.php
resources/models/V2/Account.php
resources/models/V2/Base.php
resources/models/Video.php
resources/providers/ZypeService.php
resources/services/Access.php
resources/views/auth/cc_form.php
resources/views/auth/change_credit_card.php
resources/views/auth/login_ajax.php
resources/views/auth/paywall.php
resources/views/auth/signup_ajax.php
resources/views/auth/subscription_checkout.php
resources/views/partial/player_embed.php
zype.php

[JIRA](https://zypeinc.atlassian.net/browse/CORE-3467)

 CORE 3467 - Support bundle only option

---

core.php
dist/css/zype_forms/single_video.css
dist/css/zype_forms/single_video.scss
resources/views/partial/player_embed.php
resources/views/video_single.php
zype.php

[JIRA](https://zypeinc.atlassian.net/browse/CORE-3526)

CORE 3526 - Add support for playing trailers

---

resources/views/partial/player_embed.php
zype.php

[JIRA](https://zypeinc.atlassian.net/browse/CORE-3721)
[zype-wordpress-plugin-v2.5.10.zip](https://github.com/zype/zype-wordpress-plugin/files/3150377/zype-wordpress-plugin-v2.5.10.zip)

CORE 3721 - Always show video's trailer

---

resources/lib/Zype/Api.php
resources/lib/Zype/Api/Video.php
resources/lib/Zype/config.php
resources/models/Transaction.php
resources/views/partial/player_embed.php
zype.php

[JIRA](https://zypeinc.atlassian.net/browse/CORE-3779)
[zype-wordpress-plugin-v2.5.11.zip](https://github.com/zype/zype-wordpress-plugin/files/3156317/zype-wordpress-plugin-v2.5.11.zip)

CORE 3779 - Don't cache after creating a transaction

---

dist/css/zype_forms/single_video.css
resources/lib/Zype/Api.php
resources/lib/Zype/Api/Video.php
resources/lib/Zype/config.php
resources/models/Transaction.php
resources/views/partial/player_embed.php
zype.php

[JIRA](https://zypeinc.atlassian.net/browse/CORE-3722)
[zype-wordpress-plugin-v2.5.12.zip](https://github.com/zype/zype-wordpress-plugin/files/3157091/zype-wordpress-plugin-v2.5.12.zip)

CORE 3722 - Make the button as height as it's conent

---

dist/css/zype_forms/single_video.css
resources/lib/Zype/Api.php
resources/lib/Zype/Api/Account.php
resources/lib/Zype/Api/Video.php
resources/lib/Zype/config.php
resources/models/Transaction.php
resources/services/Access.php
resources/views/partial/player_embed.php
zype.php

[zype-wordpress-plugin-v2.5.13.zip](https://github.com/zype/zype-wordpress-plugin/files/3164654/zype-wordpress-plugin-v2.5.13.zip)
[JIRA](https://zypeinc.atlassian.net/browse/CORE-3786)

CORE 3786 - Free videos doesn't require authentication anymore

---

core.php
dist/css/style_plugin.css
dist/css/zype_forms/single_video.css
dist/css/zype_forms/single_video.scss
resources/helpers.php
resources/lib/Zype/Api.php
resources/lib/Zype/Api/Account.php
resources/lib/Zype/Api/Video.php
resources/lib/Zype/config.php
resources/models/Transaction.php
resources/services/Access.php
resources/views/partial/player_embed.php
zype.php

[JIRA](https://zypeinc.atlassian.net/browse/CORE-3789)
[zype-wordpress-plugin-v2.5.14.zip](https://github.com/zype/zype-wordpress-plugin/files/3171158/zype-wordpress-plugin-v2.5.14.zip)

 CORE 3789 - Fix styles to make it work with any theme

---

dist/javascripts/zype_wp.js
resources/controllers/Consumer/Auth.php
resources/providers/HooksService.php
resources/views/auth/change_credit_card.php
resources/views/auth/change_password.php
resources/views/auth/login_ajax.php
resources/views/auth/signup_ajax.php
zype.php

[JIRA](https://zypeinc.atlassian.net/browse/CORE-3986)
1) The changing password form wasn't showing any validation. That's why when the new password wasn't being saved, it wasn't valid.
2) Applied the same criteria for sign up:
- The password must be at least 8 characters
- The password must include an uppercase letter
- The password must include a lowercase letter
- The password must include a number

CORE 3986 - Show validations when changing password. Same password validation as when changing passwords

---

resources/controllers/Admin.php
resources/controllers/Consumer/Monetization.php
resources/controllers/Consumer/Profile.php
resources/controllers/Consumer/Subscriptions.php
resources/lib/Zype/Api/Consumer.php
resources/models/V2/Consumer.php
resources/providers/ZypeService.php
resources/services/Braintree.php
resources/views/auth/subscription.php

[JIRA](https://zypeinc.atlassian.net/browse/CORE-4093)
This PR was rebased from `core-4039`
[zype-wordpress-plugin-v2.5.17.zip](https://github.com/zype/zype-wordpress-plugin/files/3429661/zype-wordpress-plugin-v2.5.17.zip)

CORE 4093 - Fix Braintree gateway

---

resources/controllers/Consumer/Subscriptions.php
resources/controllers/Consumer/Transaction.php
resources/lib/Money.php
resources/providers/ZypeService.php
resources/views/auth/cc_form.php
resources/views/auth/paywall.php
resources/views/auth/plans.php
resources/views/auth/subscription_checkout.php
src/Themosis/View/ViewServiceProvider.php

[zype-wordpress-plugin-v2.5.18.zip](https://github.com/zype/zype-wordpress-plugin/files/3460737/zype-wordpress-plugin-v2.5.18.zip)
[JIRA](https://zypeinc.atlassian.net/browse/CORE-4094)

 CORE 4094 - Transaction/Subscription successfull msg

---

resources/models/Player.php
resources/views/partial/player_embed.php
zype.php

[JIRA](https://zypeinc.atlassian.net/browse/CORE-4044)
[zype-wordpress-plugin-v2.6.1.zip](https://github.com/zype/zype-wordpress-plugin/files/3553732/zype-wordpress-plugin-v2.6.1.zip)

CORE 4044 - Include theo manually

---

Dockerfile
README.md
docker-compose.yml
resources/lib/ApiOperations/Retrieve.php
resources/models/V2/Consumer.php
resources/services/Access.php
resources/services/Auth.php
zype.php

https://zypeinc.atlassian.net/browse/CORE-5702

CORE 5702 - After subscription fetch non cached Consumer

---

Dockerfile
README.md
dist/css/zype_forms/regform.css
resources/controllers/Admin.php
resources/controllers/Consumer/Monetization.php
resources/lib/Zype/config.php
resources/views/auth/cc_form.php
zype.php

If neither Stripe or Braintre are set up show an error during checkout.

FND 771 - Return error in checkout if neither Stripe nor Braintree are set up
